# no packages yet
packages: []

# need to publish workspace root with correct version
includeWorkspaceRoot: true

strictPeerDependencies: true

onlyBuiltDependencies: []

ignoredBuiltDependencies:
  - unrs-resolver
